# Generated by Django 3.1.6 on 2021-03-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_car_door'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='paragraph',
            new_name='paragraphFirst',
        ),
        migrations.RenameField(
            model_name='door',
            old_name='paragraph',
            new_name='paragraphFirst',
        ),
        migrations.RenameField(
            model_name='grass',
            old_name='paragraph',
            new_name='paragraphFirst',
        ),
        migrations.AddField(
            model_name='car',
            name='paragraphSecond',
            field=models.CharField(blank=True, default='It is not compulsory', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='titleFirst',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='titleSecond',
            field=models.CharField(blank=True, default='It is not compulsory', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='door',
            name='paragraphSecond',
            field=models.CharField(blank=True, default='It is not compulsory', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='door',
            name='titleFirst',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='door',
            name='titleSecond',
            field=models.CharField(blank=True, default='It is not compulsory', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grass',
            name='paragraphSecond',
            field=models.CharField(blank=True, default='It is not compulsory', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='grass',
            name='titleFirst',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grass',
            name='titleSecond',
            field=models.CharField(blank=True, default='It is not compulsory', max_length=200, null=True),
        ),
    ]
