# Generated by Django 3.1.6 on 2021-03-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210323_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfProduct', models.CharField(blank=True, max_length=200, null=True)),
                ('typeOfProduct', models.CharField(choices=[('Газоны Queens Grass', 'Газоны Queens Grass'), ('Dennis UK', 'Dennis UK'), ('Sisis', 'Sisis'), ('Trilo', 'Trilo'), ('Vredo', 'Vredo'), ('Redexim', 'Redexim'), ('Harrod UK', 'Harrod UK'), ('Compact tractors', 'Compact tractors'), ('Hunter', 'Hunter'), ('Другое', 'Другое')], default='Другое', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('titleFirst', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraphFirst', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleSecond', models.CharField(blank=True, default='It is not compulsory', max_length=200, null=True)),
                ('paragraphSecond', models.CharField(blank=True, default='It is not compulsory', max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Door',
        ),
        migrations.DeleteModel(
            name='Grass',
        ),
    ]
