# Generated by Django 3.1.6 on 2021-04-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210323_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='paragraphFirst',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='paragraphSecond',
            field=models.CharField(blank=True, default='It is not compulsory', max_length=1500, null=True),
        ),
    ]
