# Generated by Django 3.1.6 on 2021-04-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20210401_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='typeOfProduct',
            field=models.CharField(choices=[('Газоны Queens Grass', 'Газоны Queens Grass'), ('Dennis UK', 'Dennis UK'), ('Sisis', 'Sisis'), ('Trilo', 'Trilo'), ('Vredo', 'Vredo'), ('Redexim', 'Redexim'), ('Harrod UK', 'Harrod UK')], default='Другое', max_length=200, null=True),
        ),
    ]
